# Generated by Django 4.2.6 on 2023-10-11 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploadAsset', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assetfile',
            old_name='loadasset',
            new_name='uploadasset',
        ),
    ]
