# Generated by Django 3.2.8 on 2023-10-04 08:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('uploadAsset', '0002_alter_uploadasset_library'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset', models.FileField(upload_to='images/company/asset_versions/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RenameField(
            model_name='uploadasset',
            old_name='crerated_at',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='uploadasset',
            name='asset',
            field=models.FileField(upload_to='images/company/asset/'),
        ),
        migrations.AddField(
            model_name='uploadasset',
            name='versions',
            field=models.ManyToManyField(blank=True, to='uploadAsset.AssetVersion'),
        ),
    ]
