# Generated by Django 4.2.6 on 2023-10-11 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploadAsset', '0002_rename_loadasset_assetfile_uploadasset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadasset',
            name='tags',
        ),
    ]
