# Generated by Django 3.2.8 on 2023-10-04 08:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('uploadAsset', '0003_auto_20231004_1424'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='name',
            new_name='tag_name',
        ),
        migrations.AddField(
            model_name='assetversion',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='uploadasset',
            name='tags',
            field=models.ManyToManyField(blank=True, default=1, to='uploadAsset.Tag'),
        ),
    ]
