# Generated by Django 4.2.6 on 2023-10-11 08:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('uploadAsset', '0003_remove_uploadasset_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadasset',
            name='image',
        ),
        migrations.AlterField(
            model_name='uploadasset',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
