# Generated by Django 3.2.8 on 2023-10-04 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadAsset', '0004_auto_20231004_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadasset',
            name='tags',
            field=models.ManyToManyField(blank=True, to='uploadAsset.Tag'),
        ),
    ]
