# Generated by Django 4.2.6 on 2023-10-11 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploadAsset', '0004_remove_uploadasset_image_alter_uploadasset_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadasset',
            name='user',
        ),
    ]
