# Generated by Django 4.2.6 on 2023-10-11 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_alter_addmember_organization_alter_addmember_user'),
        ('uploadAsset', '0005_alter_uploadasset_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadasset',
            name='asset',
        ),
        migrations.RemoveField(
            model_name='uploadasset',
            name='user',
        ),
        migrations.AddField(
            model_name='uploadasset',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.organization'),
        ),
        migrations.CreateModel(
            name='AssetFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset', models.FileField(upload_to='images/company/asset/')),
                ('uploadasset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset', to='uploadAsset.uploadasset')),
            ],
        ),
    ]
