# Generated by Django 4.2.6 on 2023-10-11 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadAsset', '0006_uploadasset_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadasset',
            name='tags',
            field=models.ManyToManyField(blank=True, to='uploadAsset.tag'),
        ),
    ]
