# Generated by Django 4.2.6 on 2023-10-11 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploadAsset', '0007_uploadasset_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadasset',
            name='user',
        ),
    ]
