# Generated by Django 4.2.6 on 2023-10-11 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_remove_organization_user_organization_owner_and_more'),
        ('uploadAsset', '0009_uploadasset_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadasset',
            name='user',
        ),
        migrations.AddField(
            model_name='uploadasset',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.organization'),
        ),
    ]
